namespace AutoInterface.Generator.Templates;

public static class CommonTemplates
{
    public const string AutoGeneratedSeparator =
        "//------------------------------------------------------------------------------";
    
    public const string AutoGeneratedAnnotation =
        $"""
         {AutoGeneratedSeparator}
         // <auto-generated>
         //     This code was generated by the AutoInterface.Generator source generator
         //
         //     Changes to this file may cause incorrect behavior and will be lost if
         //     the code is regenerated.
         // </auto-generated>
         {AutoGeneratedSeparator}
         """;
}