namespace AutoInterface.Generator.Templates;

public static class GenerateAutoInterfaceAttributeTemplate
{
    private const string AttributeName = "AutoInterface";
    private const string ClassName = $"{AttributeName}Attribute";

    public const string FullName = $"{ClassName}";
    public const string FileName = $"{ClassName}.g.cs";

    public const string Code =
        $$"""
          {{CommonTemplates.AutoGeneratedAnnotation}}

          [{{Constants.SystemAttributeUsageClass}}]
          public class {{ClassName}} : {{Constants.SystemAttribute}}
          {
          }
          """;
}