using System.Text;
using AutoInterface.Generator.Core.Descriptors;

namespace AutoInterface.Generator.Templates;

public static class GenerateInterfaceTemplate
{
    public static string FileName(in DetailedTypeDescriptor detailedTypeDescriptor)
        => $"{detailedTypeDescriptor.TypeDescriptor.Namespace}.I{detailedTypeDescriptor.TypeDescriptor.Name}.g.cs";

    public static string Render(in DetailedTypeDescriptor detailedTypeDescriptor)
    {
        var sb = new StringBuilder();

        sb.AppendLine(CommonTemplates.AutoGeneratedAnnotation);
        sb.AppendLine();
        sb.AppendLine($"namespace {detailedTypeDescriptor.TypeDescriptor.Namespace};");
        PartialClassTemplate.Render(sb, detailedTypeDescriptor);
        InterfaceTemplate.Render(sb, detailedTypeDescriptor);


        return sb.ToString();
    }
}