namespace AutoInterface.Generator.Templates;

public static class GenerateAutoInterfaceIgnoreAttributeTemplate
{
    private const string AttributeName = "AutoInterfaceIgnore";
    
    public const string ClassName = $"{AttributeName}Attribute";
    public const string FileName = $"{ClassName}.g.cs";

    public const string Code =
        $$"""
          {{CommonTemplates.AutoGeneratedAnnotation}}

          [{{Constants.SystemAttributeUsageMethod}}]
          public class {{ClassName}} : {{Constants.SystemAttribute}}
          {
          }
          """;
}