# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore 
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Generate version based on date and commit hash
      id: version
      run: |
        base_version="1.0"
        commit_count=$(git rev-list --count HEAD)
        new_version="${base_version}.${commit_count}"        
        echo "VERSION=$new_version" >> $GITHUB_ENV
      
    - name: Pack the project
      run: dotnet pack -c Release -p:PackageVersion=$VERSION --no-build --output ./nupkg ./src/AutoInterface.Generator/AutoInterface.Generator.csproj
    
    
    - name: Publish to NuGet
      run: dotnet nuget push  ./nupkg/*.nupkg -s nuget.org --api-key ${{ secrets.NUGET_API_KEY }}
      
    - name: Create GitHub Release
      id: create_release
      run: |
        # Create a GitHub release using the new version
        echo "Creating GitHub release for version $VERSION"
        gh release create "$VERSION" \
          "**/*.nupkg" \
          --title "Release $VERSION" \
          --notes "Release version $VERSION" \
          --repo $GITHUB_REPOSITORY
    
