# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore 
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      
    - name: Pack the project
      run: dotnet pack -c Release --no-build --output ./nupkg ./src/AutoInterface.Generator/AutoInterface.Generator.csproj
      
    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: AutoInterface.Generator
        path: ./nupkg/*.nupkg
    
